version: "3.2"
services:
  nats:
    image: nats
    networks:
      -  nats
  natsreplicas:
    image: nats
    networks:
    - nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 15s
  testimg:
    image: testimg:latest
    networks:
      -  nats
    environment:
      - "NATS_URI=nats://nats:4222"
networks:
  nats:
    driver: overlay
    attachable: true
  # nats-1:
  #   image: nats
  #   command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  # nats-2:
  #   image: nats
  #   command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  # nats-box:
  #   image: synadia/nats-box
